### PR TITLE
Clean exit in gbm-service

### PR DESCRIPTION
**Pull request by monochromec**
Issue mitigation: Cleanly kill all kodi (sub) processes. Per definition there can be only one application access the GDM API.

### CODE REVIEW

**Comment by monochromec** [comment]
Cleaner exit in the service using the GBM backend

**Comment by graysky2** [comment]
Sorry, what issue is this PR solving?  Are you getting unclean exits currently (I am not)?

**Comment by monochromec** [comment]
Compiled from source or installed via distro package? If the latter: what distro and what repo?

**Comment by graysky2** [comment]
There is nothing to compile

**Comment by monochromec** [comment]
More verbose: Did you compile the software (Kodi) from source when creating this systemd service or did you install the s/w from a distro repo (as your README is not too specific about these details)?

**Comment by graysky2** [comment]
Compiled from source.

**Comment by monochromec** [comment]
In that case `ps -lef | fgrep kodi` yields 

```
4 S xbmc       13244       1  0  81   1 -   700 do_wai 00:18 ?        00:00:00 /bin/sh /usr/local/bin/kodi-standalone. 
0 S xbmc       13248   13244  0  81   1 -   700 sigsus 00:18 ?        00:00:00 /bin/sh /usr/local/bin/kodi --standalone. 
0 S xbmc       13253   13248 53  81   1 - 514018 hrtime 00:18 ?       00:00:06 /usr/local/lib/kodi/kodi.bin --standalone. 
```
So using your service will leave some lingering processes.
BTW: Much faster start-up and esp. tear-down is achieved by the following:
```
ExecStart = /usr/local/lib/kodi/kodi-gbm --standalone
ExecStop=/usr/bin/pkill kodi.*
```
As there's only Kodi process involved (assuming you can live w/o crash logs and your install prefix is `/usr/local` as per default).

**Comment by graysky2** [comment]
Using `pkill` as you are proposing will result in an ungraceful exit of kodi.  Use my service as-provided and `tail -f /path/to/kodi.log` when you stop it to see how a a graceful exit looks.  Then repeat using what you are proposing to see what I mean.

**Comment by monochromec** [comment]
Not that I can see:

```2024-10-20 14:26:39.781 T:14386    info <general>: VideoInfoScanner: Finished scan. Scanning for video info took 189702 ms
2024-10-20 14:27:09.876 T:13989    info <general>: NFS is idle. Closing the remaining connections.
2024-10-20 14:30:39.879 T:13989    info <general>: Quitting due to POSIX signal
2024-10-20 14:30:39.890 T:13989    info <general>: Stopping the application...
2024-10-20 14:30:39.890 T:13989    info <general>: Stopping player
2024-10-20 14:30:39.890 T:13989    info <general>: Storing total System Uptime
2024-10-20 14:30:39.891 T:13989    info <general>: Saving settings
2024-10-20 14:30:39.897 T:13989    info <general>: Saving skin settings
2024-10-20 14:30:39.897 T:13989    info <general>: Stopping all
2024-10-20 14:30:39.897 T:13989    info <general>: ES: Stopping event server
2024-10-20 14:30:40.449 T:14403    info <general>: ES: UDP Event server stopped
2024-10-20 14:30:41.266 T:13989    info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2024-10-20 14:30:41.266 T:13989    info <general>: stopping zeroconf publishing
2024-10-20 14:30:41.270 T:13989    info <CWebserver[8080]>: Stopped
2024-10-20 14:30:41.296 T:13989    info <general>: CServiceAddonManager: failed to stop inputstream.ffmpegdirect (may have ended)
2024-10-20 14:30:41.353 T:14399    info <general>: ### [XBMC LCDproc] - Shutting down
2024-10-20 14:30:41.600 T:13989    info <general>: CServiceAddonManager: failed to stop service.xbmc.versioncheck (may have ended)
2024-10-20 14:30:41.601 T:13989    info <general>: Application stopped
2024-10-20 14:30:41.851 T:13989    info <general>: PVR Manager: Stopping
2024-10-20 14:30:42.480 T:14437    info <general>: EPG Container: Persisting unsaved events...
2024-10-20 14:30:42.481 T:14437    info <general>: EPG Container: Persisting events done
2024-10-20 14:30:42.487 T:14411    info <general>: PVR Manager: Stopped
2024-10-20 14:30:44.013 T:13989    info <general>: AddOnLog: pvr.iptvsimple: pvr.iptvsimple - ConnectionLost Could not validiate M3U after startup, but ignoring as startup is all we care about.
2024-10-20 14:30:44.014 T:13989    info <general>: Skipped 1 duplicate messages..
2024-10-20 14:30:44.014 T:13989    info <general>: ADDON: Dll Destroyed - IPTV Simple Client
2024-10-20 14:30:44.405 T:13989    info <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "linux"
2024-10-20 14:30:44.405 T:13989    info <general>: ADDON: Dll Destroyed - Joystick Support
2024-10-20 14:30:44.406 T:13989    info <general>: ADDON: Dll Destroyed - X-Arcade Tankstick Driver
2024-10-20 14:30:44.406 T:13989    info <general>: unload skin
2024-10-20 14:30:44.414 T:13989    info <general>: Unloaded skin
2024-10-20 14:30:44.450 T:13989    info <general>: unload sections
2024-10-20 14:30:44.455 T:13989    info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2024-10-20 14:30:44.456 T:13989    info <general>: ADDON: Dll Destroyed - RAR archive support
2024-10-20 14:30:44.668 T:13989    info <general>: Exiting the application.
```

Using your method results in the following systemd status:

```
Oct 20 14:54:43 htpc systemd[1]: Stopping kodi.service - Kodi Media Center...
Oct 20 14:55:13 htpc systemd[1]: kodi.service: Stopping timed out. Terminating.
Oct 20 14:55:13 htpc systemd[1]: kodi.service: Control process exited, code=killed, status=15/TERM
Oct 20 14:55:43 htpc systemd[1]: kodi.service: State 'final-sigterm' timed out. Killing.
Oct 20 14:55:43 htpc systemd[1]: kodi.service: Killing process 16325 (kodi.bin) with signal SIGKILL.
Oct 20 14:55:43 htpc systemd[1]: kodi.service: Failed to kill control group /system.slice/kodi.service, ignoring: Invalid argument
Oct 20 14:55:43 htpc systemd[1]: kodi.service: Failed with result 'timeout'.
Oct 20 14:55:43 htpc systemd[1]: kodi.service: Unit process 16325 (kodi.bin) remains running after unit stopped.
Oct 20 14:55:43 htpc systemd[1]: Stopped kodi.service - Kodi Media Center.
```

Note the 60 seconds wait until it runs into a timeout.

Environment: Kodi Omega (21.1) compiled from source running on a stock Noble with gbm as backend.

**Comment by graysky2** [comment]
In my testing using your method, no entries are written to the log file, the uptime is not updated.  I do not see a 60 sec timeout ever reached, takes 3-5 to cleanly exit.

**Pull request closed without merging**
